# Generated by Django 5.1.7 on 2025-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_office_latitude_user_office_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isTrusted',
            field=models.BooleanField(default=False),
        ),
    ]
