# Generated by Django 5.1.7 on 2025-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='agreements/', verbose_name='Документ договора'),
        ),
    ]
